# Generated by Django 4.1.3 on 2022-11-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('producer', models.CharField(max_length=50)),
                ('scenario', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('trailer', models.URLField(null=True)),
            ],
        ),
    ]
